### ISSUE TITLE
Error antara field endpoint dengan url isinya sama

### ISSUE THREAD

**Issue by Ridhoardhiansyah7** [KatowProject/komikato_py#4]
"link": {
        "url": "https://komikindo.pw/komik/oppai-momu-hoho-wakatta-wa/",
        "endpoint": "https://komikindo.pw/komik/oppai-momu-hoho-wakatta-wa/"
      }

**Comment by KatowProject** [comment]
habis ganti domain, nanti diupdate lagi. makasih dah infoin sebelumnya
